# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 505)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setStyleSheet("border-image url(:/background/run.png)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qtCodeArea = QTextEditWithLineNum(self.centralwidget)
        self.qtCodeArea.setObjectName("qtCodeArea")
        self.horizontalLayout_2.addWidget(self.qtCodeArea)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qtElementArea = QTextEditWithLineNum(self.centralwidget)
        self.qtElementArea.setObjectName("qtElementArea")
        self.verticalLayout.addWidget(self.qtElementArea)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.qtMatrixArea = QtWidgets.QTableWidget(self.centralwidget)
        self.qtMatrixArea.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.qtMatrixArea.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.qtMatrixArea.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.qtMatrixArea.setObjectName("qtMatrixArea")
        self.qtMatrixArea.setColumnCount(0)
        self.qtMatrixArea.setRowCount(0)
        self.qtMatrixArea.horizontalHeader().setDefaultSectionSize(25)
        self.verticalLayout.addWidget(self.qtMatrixArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.menuBar.setObjectName("menuBar")
        self.File = QtWidgets.QMenu(self.menuBar)
        self.File.setObjectName("File")
        MainWindow.setMenuBar(self.menuBar)
        self.actionopen = QtGui.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionopen_code = QtGui.QAction(MainWindow)
        self.actionopen_code.setObjectName("actionopen_code")
        self.File.addAction(self.actionopen)
        self.File.addAction(self.actionsave)
        self.File.addSeparator()
        self.File.addAction(self.actionopen_code)
        self.menuBar.addAction(self.File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bug Localization"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))
        self.pushButton_3.setText(_translate("MainWindow", "运行"))
        self.qtElementArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.qtMatrixArea.setSortingEnabled(False)
        self.File.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "open..."))
        self.actionsave.setText(_translate("MainWindow", "save..."))
        self.actionopen_code.setText(_translate("MainWindow", "code  open..."))
from qtexteditwithlinenum import QTextEditWithLineNum
