# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 422)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.qtCodeArea = QTextEditWithLineNum(self.centralwidget)
        self.qtCodeArea.setObjectName("qtCodeArea")
        self.gridLayout.addWidget(self.qtCodeArea, 0, 0, 2, 1)
        self.qtElementArea = QTextEditWithLineNum(self.centralwidget)
        self.qtElementArea.setObjectName("qtElementArea")
        self.gridLayout.addWidget(self.qtElementArea, 0, 1, 1, 1)
        self.qtMatrixArea = QtWidgets.QTableView(self.centralwidget)
        self.qtMatrixArea.setObjectName("qtMatrixArea")
        self.gridLayout.addWidget(self.qtMatrixArea, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 674, 24))
        self.menuBar.setObjectName("menuBar")
        self.menufile = QtWidgets.QMenu(self.menuBar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionopen = QtGui.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionsave)
        self.menuBar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qtElementArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "open..."))
        self.actionsave.setText(_translate("MainWindow", "save..."))
from qtexteditwithlinenum import QTextEditWithLineNum
